backend:
  branch: main
  name: github
  repo: anartisticengineer/apxnr-portfolio
  base_url: "https://sveltia-cms-auth.justinanthonyjohnson1995.workers.dev"
  commit_messages:
    create: "Create"
    update: "Update"
    delete: "Delete"
    uploadMedia: "Upload"
    deleteMedia: "Delete"
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
site_url: "https://apxnr.netlify.app"
collections:
  - label: Pages
    name: pages
    files:
      # Home Page
      - label: "Home Page"
        name: "homepage"
        create: true
        extension: "json"
        file: "src/content/pages/homepage.json"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Call to Action"
            name: "call-to-action"
            widget: "object"
            fields:
              - {
                  label: "Call to Action Subtitle",
                  name: "call-to-action-text",
                  widget: "string",
                }
              - {
                  label: "Call to Action Button Text",
                  name: "call-to-action-btn-text",
                  widget: "string",
                }
              - {
                  label: "Call to Action Goto Link",
                  name: "call-to-action-goto-link",
                  widget: "string",
                }
      # About Me Page
      - label: "About Me"
        name: "about-me"
        create: true
        extension: "json"
        file: "src/content/pages/about-me.json"
        fields:
          - label: "Profile Pic"
            name: "profile-pic"
            widget: "object"
            fields:
              - {
                  label: "Profile Image",
                  name: "profile-image",
                  widget: "image",
                }
              - {
                  label: "Profile Alt Text",
                  name: "profile-alt-text",
                  widget: "string",
                }
          - label: "Summary"
            name: summary
            widget: "markdown"
      # Contact Page
      - label: "Contact"
        name: "contact"
        create: true
        extension: "json"
        file: "src/content/pages/contact.json"
        fields:
          - label: "Message"
            name: "message"
            widget: "markdown"
      # Gallery Pages
      - label: "Gallery"
        name: "gallery"
        create: true
        extension: "json"
        file: "src/content/pages/gallery.json"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - {
                  label: "Description",
                  name: "description",
                  widget: "markdown",
                  required: false,
                }
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - {
                      label: "Image",
                      name: "image",
                      widget: "image",
                      allow_multiple: false,
                    }
                  - {
                      label: "Alt Text",
                      name: "alt-text",
                      widget: "string",
                      required: false,
                    }
  # ~~~~~~~~Components~~~~~~~
  - label: Components
    name: components
    files:
      # Header
      - label: "Header"
        name: "header"
        create: true
        extension: "json"
        file: "src/content/components/header.json"
        fields:
          # Home Image/Logo
          - label: "Home Image"
            name: "home-image"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt-text", widget: "string" }
      # Footer
      - label: "Footer"
        name: "footer"
        create: true
        extension: "json"
        file: "src/content/components/footer.json"
        fields:
          - label: "Socials"
            name: "socials"
            widget: "list"
            fields:
              - { label: "Site name", name: "site-name", widget: "string" }
              - {
                  label: "Site link",
                  name: "site-link",
                  widget: "string",
                  pattern: ["^https:\/\/", "Must be a valid URL"],
                }
